/**
 * database/models/AIRecommendation.js
 * Stores the latest AI-generated academic risk analysis for a student.
 * Generated by backend/services/aiService.js (see that file for logic).
 */

const mongoose = require('mongoose');
const { Schema } = mongoose;

const aiRecommendationSchema = new Schema(
  {
    student: {
      type: Schema.Types.ObjectId,
      ref: 'Student',
      required: true,
    },
    riskLevel: {
      type: String,
      enum: ['LOW', 'MEDIUM', 'HIGH'],
      required: true,
    },
    weakSubjects: [
      {
        type: String,
        trim: true,
      },
    ],
    observations: [
      {
        type: String,
        trim: true,
      },
    ],
    recommendations: [
      {
        type: String,
        trim: true,
      },
    ],
    metrics: {
      attendancePercentage: { type: Number, min: 0, max: 100 },
      assignmentAverage: { type: Number, min: 0, max: 100 },
      examAverage: { type: Number, min: 0, max: 100 },
    },
    source: {
      type: String,
      enum: ['AI', 'FALLBACK'],
      default: 'FALLBACK',
    },
    generatedAt: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true }
);

aiRecommendationSchema.index({ student: 1, generatedAt: -1 });

module.exports =
  mongoose.models.AIRecommendation || mongoose.model('AIRecommendation', aiRecommendationSchema);
